### ISSUE TITLE
Изменить цены на товары

### ISSUE THREAD

**Issue by AndreiBakhtinov** [AndreiBakhtinov/Sandbox#5]
Для товаров из категории 1 и 2 в ценовом дипазоне от 50 до 100 добавить наценку 15.5%
https://www.w3schools.com/sql/trysql.asp?filename=trysql_select_all

**Comment by WheelyHog** [comment]
UPDATE products
SET price = price * 1.155
WHERE
    category IN (1, 2)
    AND price BETWEEN 50 AND 100;
